# Caminho do projeto React
react.project.path=C:\workspace\repository-frontend

# Caminho do projeto Java (Spring, por exemplo)
java.project.path=C:\workspace\repository5

# Comando para build do React
react.build.command=npm run build

# Pasta de saída do React (dist ou build)
react.dist.folder=dist

# Nome da pasta do Java dentro de tools/java
java.version.folder=jdk-17